export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE'
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS' 

export const ADD_QUESTION = 'ADD_QUESTION'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE'

export const SELECT_QUESTION = 'SELECT_QUESTION'
export const SELECT_QUESTION_SUCCESS = 'SELECT_QUESTION_SUCCESS'
export const SELECT_QUESTION_FAILURE = 'SELECT_QUESTION_FAILURE'
export const RESET_SELECT_QUESTION = 'RESET_SELECT_QUESTION'

export const UPDATE_QUESTION = 'UPDATE_QUESTION'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAILURE = 'UPDATE_QUESTION_FAILURE'

export const DELETE_QUESTION = 'DELETE_QUESTION'
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE'